# This is a basic workflow to help you get started with Actions

name: CI

strategy:
  matrix:
    node-version: [12.x]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Test build
        run: npm run build
